bias.pl sucessfully generated!!!
bk.pl sucessfully generated!!!
exs.pl sucessfully generated!!!
17:53:03 Num. pos examples: 8
17:53:03 Num. neg examples: 92
17:53:03 Searching programs of size: 3
17:53:05 Searching programs of size: 4
17:53:55 Searching programs of size: 5
[Thread 1]: failed to recover from local-overflow
C-stack trace labeled "out-of-stack":
  [0] save_backtrace() at  [0x1062721dc]
  [1] outOfStack() at  [0x106240734]
  [2] raiseStackOverflow() at  [0x106240d38]
  [3] PL_new_term_ref___LD() at  [0x1062460f0]
  [4] ffi_call_SYSV() at  [0x1018f8050]
  [5] ffi_call_int() at  [0x1018f5868]
  [6] _ctypes_callproc() at  [0x101e881c4]
  [7] PyCFuncPtr_call() at  [0x101e7d268]
  [8] /opt/miniconda3/envs/numsynth/bin/python3.13(_PyObject_MakeTpCall+0x154) [0x1010782b4]
  [9] /opt/miniconda3/envs/numsynth/bin/python3.13(_PyEval_EvalFrameDefault+0x5514) [0x1011f8ef8]
  [10] /opt/miniconda3/envs/numsynth/bin/python3.13(gen_send_ex2+0x31c) [0x10109d55c]
  [11] /opt/miniconda3/envs/numsynth/bin/python3.13(gen_iternext+0x38) [0x10109cfa0]
  [12] /opt/miniconda3/envs/numsynth/bin/python3.13(list_extend_iter_lock_held+0x110) [0x1010b4a74]
  [13] /opt/miniconda3/envs/numsynth/bin/python3.13(list_vectorcall+0x1d0) [0x1010b3dac]
  [14] /opt/miniconda3/envs/numsynth/bin/python3.13(_PyEval_EvalFrameDefault+0x3828) [0x1011f720c]
  [15] /opt/miniconda3/envs/numsynth/bin/python3.13(PyEval_EvalCode+0x134) [0x1011f27a0]
  [16] /opt/miniconda3/envs/numsynth/bin/python3.13(run_eval_code_obj+0x10c) [0x101285020]
  [17] /opt/miniconda3/envs/numsynth/bin/python3.13(run_mod+0xe0) [0x101285148]
  [18] /opt/miniconda3/envs/numsynth/bin/python3.13(_PyRun_SimpleFileObject+0x688) [0x101284a18]
  [19] /opt/miniconda3/envs/numsynth/bin/python3.13(_PyRun_AnyFileObject+0x128) [0x101283918]
  [20] /opt/miniconda3/envs/numsynth/bin/python3.13(pymain_run_file+0x190) [0x1012b3b00]
  [21] /opt/miniconda3/envs/numsynth/bin/python3.13(Py_RunMain+0xb34) [0x1012b325c]
  [22] /opt/miniconda3/envs/numsynth/bin/python3.13(pymain_main+0x2cc) [0x1012b4c80]
  [23] /opt/miniconda3/envs/numsynth/bin/python3.13(main+0x38) [0x100fffb20]
  [24] /usr/lib/dyld(start+0x1c10) [0x19c489d54]
C-stack trace labeled "crash":
  [0] save_backtrace() at  [0x1062721dc]
  [1] outOfStack() at  [0x106240c78]
  [2] raiseStackOverflow() at  [0x106240d38]
  [3] PL_new_term_ref___LD() at  [0x1062460f0]
  [4] ffi_call_SYSV() at  [0x1018f8050]
  [5] ffi_call_int() at  [0x1018f5868]
  [6] _ctypes_callproc() at  [0x101e881c4]
  [7] PyCFuncPtr_call() at  [0x101e7d268]
  [8] /opt/miniconda3/envs/numsynth/bin/python3.13(_PyObject_MakeTpCall+0x154) [0x1010782b4]
  [9] /opt/miniconda3/envs/numsynth/bin/python3.13(_PyEval_EvalFrameDefault+0x5514) [0x1011f8ef8]
  [10] /opt/miniconda3/envs/numsynth/bin/python3.13(gen_send_ex2+0x31c) [0x10109d55c]
  [11] /opt/miniconda3/envs/numsynth/bin/python3.13(gen_iternext+0x38) [0x10109cfa0]
  [12] /opt/miniconda3/envs/numsynth/bin/python3.13(list_extend_iter_lock_held+0x110) [0x1010b4a74]
  [13] /opt/miniconda3/envs/numsynth/bin/python3.13(list_vectorcall+0x1d0) [0x1010b3dac]
  [14] /opt/miniconda3/envs/numsynth/bin/python3.13(_PyEval_EvalFrameDefault+0x3828) [0x1011f720c]
  [15] /opt/miniconda3/envs/numsynth/bin/python3.13(PyEval_EvalCode+0x134) [0x1011f27a0]
  [16] /opt/miniconda3/envs/numsynth/bin/python3.13(run_eval_code_obj+0x10c) [0x101285020]
  [17] /opt/miniconda3/envs/numsynth/bin/python3.13(run_mod+0xe0) [0x101285148]
  [18] /opt/miniconda3/envs/numsynth/bin/python3.13(_PyRun_SimpleFileObject+0x688) [0x101284a18]
  [19] /opt/miniconda3/envs/numsynth/bin/python3.13(_PyRun_AnyFileObject+0x128) [0x101283918]
  [20] /opt/miniconda3/envs/numsynth/bin/python3.13(pymain_run_file+0x190) [0x1012b3b00]
  [21] /opt/miniconda3/envs/numsynth/bin/python3.13(Py_RunMain+0xb34) [0x1012b325c]
  [22] /opt/miniconda3/envs/numsynth/bin/python3.13(pymain_main+0x2cc) [0x1012b4c80]
  [23] /opt/miniconda3/envs/numsynth/bin/python3.13(main+0x38) [0x100fffb20]
  [24] /usr/lib/dyld(start+0x1c10) [0x19c489d54]
[FATAL ERROR: at Sat Sep 20 17:56:38 2025
	Sorry, cannot continue]
[Thread 1]: failed to recover from local-overflow
C-stack trace labeled "out-of-stack":
  [0] save_backtrace() at  [0x1062721dc]
  [1] outOfStack() at  [0x106240734]
  [2] raiseStackOverflow() at  [0x106240d38]
  [3] PL_new_term_ref___LD() at  [0x1062460f0]
  [4] ffi_call_SYSV() at  [0x1018f8050]
  [5] ffi_call_int() at  [0x1018f5868]
  [6] _ctypes_callproc() at  [0x101e881c4]
  [7] PyCFuncPtr_call() at  [0x101e7d268]
  [8] /opt/miniconda3/envs/numsynth/bin/python3.13(_PyObject_MakeTpCall+0x154) [0x1010782b4]
  [9] /opt/miniconda3/envs/numsynth/bin/python3.13(_PyEval_EvalFrameDefault+0x5514) [0x1011f8ef8]
  [10] /opt/miniconda3/envs/numsynth/bin/python3.13(gen_send_ex2+0x31c) [0x10109d55c]
  [11] /opt/miniconda3/envs/numsynth/bin/python3.13(gen_iternext+0x38) [0x10109cfa0]
  [12] /opt/miniconda3/envs/numsynth/bin/python3.13(list_extend_iter_lock_held+0x110) [0x1010b4a74]
  [13] /opt/miniconda3/envs/numsynth/bin/python3.13(list_vectorcall+0x1d0) [0x1010b3dac]
  [14] /opt/miniconda3/envs/numsynth/bin/python3.13(_PyEval_EvalFrameDefault+0x3828) [0x1011f720c]
  [15] /opt/miniconda3/envs/numsynth/bin/python3.13(PyEval_EvalCode+0x134) [0x1011f27a0]
  [16] /opt/miniconda3/envs/numsynth/bin/python3.13(run_eval_code_obj+0x10c) [0x101285020]
  [17] /opt/miniconda3/envs/numsynth/bin/python3.13(run_mod+0xe0) [0x101285148]
  [18] /opt/miniconda3/envs/numsynth/bin/python3.13(_PyRun_SimpleFileObject+0x688) [0x101284a18]
  [19] /opt/miniconda3/envs/numsynth/bin/python3.13(_PyRun_AnyFileObject+0x128) [0x101283918]
  [20] /opt/miniconda3/envs/numsynth/bin/python3.13(pymain_run_file+0x190) [0x1012b3b00]
  [21] /opt/miniconda3/envs/numsynth/bin/python3.13(Py_RunMain+0xb34) [0x1012b325c]
  [22] /opt/miniconda3/envs/numsynth/bin/python3.13(pymain_main+0x2cc) [0x1012b4c80]
  [23] /opt/miniconda3/envs/numsynth/bin/python3.13(main+0x38) [0x100fffb20]
  [24] /usr/lib/dyld(start+0x1c10) [0x19c489d54]
C-stack trace labeled "crash":
  [0] save_backtrace() at  [0x1062721dc]
  [1] outOfStack() at  [0x106240c78]
  [2] raiseStackOverflow() at  [0x106240d38]
  [3] PL_open_foreign_frame___LD() at  [0x106198c10]
  [4] checkPrologFlagsAccess() at  [0x106275058]
  [5] PL_cleanup() at  [0x10621c3a0]
  [6] haltProlog() at  [0x10624e178]
  [7] PL_abort_process() at  [0x10624e1c8]
  [8] vfatalError() at  [0x10621ca10]
  [9] PL_set_resource_db_mem() at  [0x10621c204]
  [10] outOfStack() at  [0x106240c8c]
  [11] raiseStackOverflow() at  [0x106240d38]
  [12] PL_new_term_ref___LD() at  [0x1062460f0]
  [13] ffi_call_SYSV() at  [0x1018f8050]
  [14] ffi_call_int() at  [0x1018f5868]
  [15] _ctypes_callproc() at  [0x101e881c4]
  [16] PyCFuncPtr_call() at  [0x101e7d268]
  [17] /opt/miniconda3/envs/numsynth/bin/python3.13(_PyObject_MakeTpCall+0x154) [0x1010782b4]
  [18] /opt/miniconda3/envs/numsynth/bin/python3.13(_PyEval_EvalFrameDefault+0x5514) [0x1011f8ef8]
  [19] /opt/miniconda3/envs/numsynth/bin/python3.13(gen_send_ex2+0x31c) [0x10109d55c]
  [20] /opt/miniconda3/envs/numsynth/bin/python3.13(gen_iternext+0x38) [0x10109cfa0]
  [21] /opt/miniconda3/envs/numsynth/bin/python3.13(list_extend_iter_lock_held+0x110) [0x1010b4a74]
  [22] /opt/miniconda3/envs/numsynth/bin/python3.13(list_vectorcall+0x1d0) [0x1010b3dac]
  [23] /opt/miniconda3/envs/numsynth/bin/python3.13(_PyEval_EvalFrameDefault+0x3828) [0x1011f720c]
  [24] /opt/miniconda3/envs/numsynth/bin/python3.13(PyEval_EvalCode+0x134) [0x1011f27a0]
  [25] /opt/miniconda3/envs/numsynth/bin/python3.13(run_eval_code_obj+0x10c) [0x101285020]
  [26] /opt/miniconda3/envs/numsynth/bin/python3.13(run_mod+0xe0) [0x101285148]
  [27] /opt/miniconda3/envs/numsynth/bin/python3.13(_PyRun_SimpleFileObject+0x688) [0x101284a18]
  [28] /opt/miniconda3/envs/numsynth/bin/python3.13(_PyRun_AnyFileObject+0x128) [0x101283918]
  [29] /opt/miniconda3/envs/numsynth/bin/python3.13(pymain_run_file+0x190) [0x1012b3b00]
  [30] /opt/miniconda3/envs/numsynth/bin/python3.13(Py_RunMain+0xb34) [0x1012b325c]
  [31] /opt/miniconda3/envs/numsynth/bin/python3.13(pymain_main+0x2cc) [0x1012b4c80]
  [32] /opt/miniconda3/envs/numsynth/bin/python3.13(main+0x38) [0x100fffb20]
  [33] /usr/lib/dyld(start+0x1c10) [0x19c489d54]
execution time: 217s
