bk.pl sucessfully generated!!!
exs.pl sucessfully generated!!!
/Users/edoardosarri/Documents/prediction-in-data-driven-system/numsynth/popper/tester.py:9: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
11:25:41 Num. pos examples: 72
11:25:41 Num. neg examples: 28
11:25:41 Searching programs of size: 3
11:25:43 Searching programs of size: 4
11:25:45 Searching programs of size: 5
Traceback (most recent call last):
  File "/Users/edoardosarri/Documents/prediction-in-data-driven-system/numsynth/popper.py", line 8, in <module>
    prog, score, stats = learn_solution(settings)
                         ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/edoardosarri/Documents/prediction-in-data-driven-system/numsynth/popper/loop.py", line 263, in learn_solution
    timeout(settings, popper, (settings,), timeout_duration=int(settings.timeout),)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edoardosarri/Documents/prediction-in-data-driven-system/numsynth/popper/util.py", line 86, in timeout
    result = func(*args, **kwargs)
  File "/Users/edoardosarri/Documents/prediction-in-data-driven-system/numsynth/popper/loop.py", line 92, in popper
    instantiated_programs, properties = tester.test_prog(prog, selector.solution_found, settings=settings)
                                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edoardosarri/Documents/prediction-in-data-driven-system/numsynth/popper/tester.py", line 135, in test_prog
    return self.lazy_evaluation(settings, rules, numerical_reasoning, solution_found)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edoardosarri/Documents/prediction-in-data-driven-system/numsynth/popper/tester.py", line 177, in lazy_evaluation
    properties, mapping, var_clause = list(self.find_binding_prolog_numerical(settings, list(self.pos_index.keys()), rules))
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edoardosarri/Documents/prediction-in-data-driven-system/numsynth/popper/tester.py", line 262, in find_binding_prolog_numerical
    bindings = list((self.prolog.query(f'lazy_evaluation({list(pos)}, {[pred]},{[arity]},'
                                       f'{magic_args_list},{related_args_list},'
                                       f'NoSub, Pruned, Bindings)')))
  File "/opt/miniconda3/envs/numsynth/lib/python3.13/site-packages/pyswip/prolog.py", line 171, in __call__
    raise PrologError(
    ...<10 lines>...
    )
pyswip.prolog.PrologError: Caused by: 'lazy_evaluation([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72], ['failure'],[1],[[]],[[2]],NoSub, Pruned, Bindings)'. Returned: 'error(resource_error(stack), {'choicepoints': 7, 'depth': 8, 'environments': 7, 'globalused': 3, 'localused': 2, 'stack': [Functor(582029,3,8,:(system, $add_findall_bag(/(-, 2))),[]), Functor(582029,3,7,:($bags, findall_loop(/(-, 2), /(:, 2), _1058, [])),[]), Functor(582029,3,6,:($bags, cleanup_bag(/(:, 2), /(:, 2))),[]), Functor(582029,3,3,:(user, find_bindings([72], [1], [1], [1], [1], _1132)),[]), Functor(582029,3,2,:(user, lazy_evaluation([72], [1], [1], [1], [1], _1190, false, _1194)),[])], 'stack_limit': 1048576, 'trailused': 0})'.
execution time: 56s
